backend:
  name: git-gateway
  repo: rzecchini/giulialanaro # Path to your Github repository
  branch: master # Branch to update

media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "moodboards" # Used in routes, e.g., /admin/collections/blog
    label: "Moodboards" # Used in the UI
    folder: "_moodboards" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - label: "Images"
        name: "images"
        required: false
        widget: "list"
        fields:
        - {label: "Picture", name: "picture", widget: "image"}
        - {label: "Dida", name: "dida", widget: "string"}
